# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 21:06
from __future__ import unicode_literals

from django.db import migrations


def re_orient_tasks_to_new_apps(apps, schema_editor):
    PeriodicTask = apps.get_model('django_celery_beat',
                                  'PeriodicTask')

    PeriodicTask.objects.select_for_update()\
        .filter(task='marketing.tasks.update_slack_membership_cache')\
        .update(task='slack.tasks.update_slack_membership_cache')

    PeriodicTask.objects.select_for_update() \
        .filter(task='marketing.tasks.capture_snapshot_of_user_count') \
        .update(task='slack.tasks.capture_snapshot_of_user_count')


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_auto_20170729_2047'),
    ]

    operations = [
        migrations.RunPython(re_orient_tasks_to_new_apps),
    ]
